"use client"
import { type NextPage } from "next";
import Head from "next/head";
import { useState } from "react";
import { useSession } from "next-auth/react";

const Home: NextPage = () => {
  const [count, setCount] = useState(0);
  console.log("Hello World!")
  const { data: session, status, } = useSession();


  if (status === "unauthenticated") {
    console.log("unauthenticated")
  }
  else if (status === "loading") {
    console.log("laoding")
  } else {
    console.log("authenticated", session)
  }
  return (
    <>
      <Head>
        <title>Athena</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="container">
        <h1>welcome to Athena</h1>
      </div>
    </>
  );
};

export default Home;
